# Generated by Django 6.0.6 on 2026-08-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='billing_day',
            new_name='buyer_billing_day',
        ),
    ]
